"""reference generation : PublicContracts × ProviderDeclarations × CatalogueTables → Markdown.

The local entry point reads shipped contracts and catalogue facts without resolving
credentials, opening observation stores or calling a source.
"""

from __future__ import annotations

import argparse
import inspect
from importlib import import_module
from pathlib import Path
from types import FunctionType

import polars as pl

import rivretrieve
from rivretrieve._internal.drainage_areas import DRAINAGE_AREA_SCHEMA
from rivretrieve._internal.observations import ObservationDataSchema
from rivretrieve._internal.provider_manifest import BUILTIN_PROVIDER_IDS
from rivretrieve._internal.providers.registration import BulkStore, CatalogueOnly, LiveStages, load_manifest
from rivretrieve._internal.selection import SELECTION_FRAME_SCHEMA

# These are returned-domain contracts, not additional top-level exports.
TYPE_LOCATIONS = {
    "selection": ("_Selection", "_Series"),
    "observations": ("ObservationResult", "ObservationProvenance", "Receipts", "ReceiptEntry", "StoreExcerptReceipt"),
    "issues": ("Issue",),
    "catalogues.evidence": ("CatalogueEvidence",),
    "coverage": ("RequestedInterval", "CoverageInterval"),
    "engine": ("SourceCallOrigin",),
    "store.reader": ("StoreStatus",),
    "store.validation": ("ValidatedStore", "StoreManifest", "AccumulatedStoreManifest"),
    "bulk": ("CacheClearResult",),
}
EXCEPTION_LOCATIONS = {
    "discovery": ("EmptySelectionError", "MultiProviderSelectionError"),
    "registry": ("UnknownProviderError",),
    "selection": ("UnknownStationError", "UnknownProductError"),
    "issues": (
        "RivRetrieveError",
        "FatalContractError",
        "IssuePolicyError",
        "InvalidObservationRequestError",
        "MissingCredentialError",
        "MissingOptionalDependencyError",
        "ObservationsUnavailableError",
        "ObservationDataSchemaError",
    ),
    "bulk": ("BulkOperationsUnavailableError", "BulkArtifactCleanupRefusedError", "InsufficientDiskSpaceError"),
    "store.validation": ("ObservationStoreRefusedError",),
    "store.certification": ("StoreCertificationError", "StorePostCommitCleanupError"),
}


def _doc_markdown(doc: str) -> str:
    lines = inspect.cleandoc(doc).splitlines()
    output: list[str] = []
    section = ""
    index = 0
    while index < len(lines):
        line = lines[index]
        if index + 1 < len(lines) and lines[index + 1] and set(lines[index + 1]) == {"-"}:
            section = line
            output.extend((f"#### {section}", ""))
            index += 2
            continue
        if section in {"Parameters", "Returns", "Raises", "Attributes"} and line:
            if not line.startswith(" "):
                output.append(f"- **{line.replace('`', '')}**")
            else:
                output.append("  " + line.strip().replace("``", "`"))
        else:
            output.append(line.replace("``", "`"))
        index += 1
    return "\n".join(output)


def _contract(name: str, value: FunctionType | type, *, public: bool) -> str:
    location = f"{value.__module__}.{value.__name__}"
    doc = inspect.getdoc(value)
    if not doc:
        raise ValueError(f"Missing reference docstring: {location}")
    header = f"### `{name}`\n\n"
    if public:
        header += f"```text\nrivretrieve.{name}{inspect.signature(value)}\n```\n\n"
        header += f"Import: `from rivretrieve import {name}`.\n\n"
    else:
        header += f"Type location: `{location}`.\n\n"
    return header + _doc_markdown(doc) + "\n"


def _schema(title: str, schema: pl.Schema) -> str:
    rows = [f"### {title}", "", "| Column | Polars dtype |", "| --- | --- |"]
    rows.extend(f"| `{name}` | `{dtype}` |" for name, dtype in schema.items())
    return "\n".join(rows) + "\n"


def render_reference() -> str:
    """Read local shipped contracts and return their deterministic Markdown reference.

    This is the offline composition root. It does not call providers(), whose
    credential-readiness check reads the working directory's .env file.
    """
    public_functions = [
        (name, value)
        for name, value in vars(rivretrieve).items()
        if not name.startswith("_") and inspect.isfunction(value)
    ]
    public_functions.sort()
    parts = [
        "# API and capability reference\n",
        "[Documentation index](README.md)\n",
        "Generated from public function docstrings, returned-domain contracts, schemas, "
        "provider declarations and packaged catalogue tables. Do not edit this file directly.\n",
        "Regenerate locally with `uv run python scripts/generate_reference.py`. "
        "Check drift with `uv run python scripts/generate_reference.py --check`. "
        "Neither command retrieves observations, resolves credentials or reads `.env`.\n",
        "## Public functions\n",
        "The signatures below preserve runtime annotations and defaults. "
        "Some annotations are broader than accepted inputs or omit the return type. "
        "Parameters and Returns document the effective contracts. "
        "All functions import from `rivretrieve`.\n",
        "\n".join(f"- [{name}](#{name})" for name, _ in public_functions) + "\n",
    ]
    parts.extend(_contract(name, value, public=True) for name, value in public_functions)
    parts.extend(
        (
            "## Frame schemas\n",
            _schema("Selection frame", SELECTION_FRAME_SCHEMA),
            "See `_Series` below for column meanings. Published record bounds and "
            "native_id can be absent. Availability unknown remains selectable.\n",
            _schema("Drainage-area frame", DRAINAGE_AREA_SCHEMA),
            "See `drainage_areas` above and [drainage-area metadata](drainage-areas.md) for JSON decoding and absence states.\n",
            _schema("Observation frame", ObservationDataSchema.polars_schema),
            "Only value is nullable. Time precision can vary while remaining Datetime. "
            "The zone belongs to each row, not the timestamp dtype. "
            "See `ObservationResult` below for units and meanings.\n",
            "## Returned domain types\n",
            "These types are not re-exported from `rivretrieve`. "
            "Their locations below identify the current implementation. "
            "Create selections through the public functions rather than constructing `_Selection`.\n",
        )
    )
    for suffix, names in TYPE_LOCATIONS.items():
        module = import_module(f"rivretrieve._internal.{suffix}")
        parts.extend(_contract(name, getattr(module, name), public=False) for name in names)
        if suffix == "observations":
            for method in (module.ObservationResult.to_polars, module.ObservationResult.to_pandas):
                name = f"ObservationResult.{method.__name__}"
                parts.append(
                    f"### `{name}`\n\n```text\n{name}{inspect.signature(method)}\n```\n\n"
                    + _doc_markdown(inspect.getdoc(method) or "")
                    + "\n"
                )
    parts.extend(
        (
            "## Exception imports\n",
            "Function Raises sections state the conditions. FatalContractError subclasses "
            "bypass the caller issue policy. IssuePolicyError carries its actionable issues. "
            "Local I/O and bulk transfer failures can also propagate.\n",
            "| Exception | Import module | Base class |\n| --- | --- | --- |",
        )
    )
    for suffix, names in EXCEPTION_LOCATIONS.items():
        module = import_module(f"rivretrieve._internal.{suffix}")
        for name in names:
            value = getattr(module, name)
            parts.append(f"| `{name}` | `{module.__name__}` | `{value.__bases__[0].__name__}` |")
    parts.extend(
        (
            "\n## Shipped software capabilities\n",
            "The table uses the built-in manifest and declarations, not source probes. "
            "Credential names are requirements, not a readiness or successful-access test. "
            "Bulk retrieval needs explicit `download()` consent before a store exists.\n",
            "Counts describe packaged inventory accounting only. They do not establish "
            "countrywide completeness, continuous history or present-day source access. "
            "Available and unknown pairs are selectable. Unavailable pairs are not. "
            "See the [provider handoff](README.md#providers) for ownership and coverage qualifications.\n",
            "| Provider | Observation kind | Required credential variables | Stations | Available pairs | Unknown pairs | Unavailable pairs |\n"
            "| --- | --- | --- | ---: | ---: | ---: | ---: |",
        )
    )
    products: list[str] = []
    for declared in load_manifest(BUILTIN_PROVIDER_IDS):
        declaration = declared.declaration
        kind = declaration.observations
        if isinstance(kind, LiveStages):
            label = "live"
        elif isinstance(kind, BulkStore):
            label = "bulk store"
        elif isinstance(kind, CatalogueOnly):
            label = "catalogue-only"
        else:
            raise TypeError(f"Unrecognized provider kind: {type(kind)}")
        credentials = ", ".join(f"`{name}`" for name in declaration.required_credentials) or "none"
        stations = pl.read_parquet(declaration.catalogue / "stations.parquet").height
        pairs = pl.read_parquet(declaration.catalogue / "station_products.parquet")
        counts = [
            pairs.filter(pl.col("availability") == state).height for state in ("available", "unknown", "unavailable")
        ]
        parts.append(
            f"| `{declared.provider_id}` | {label} | {credentials} | {stations} | "
            + " | ".join(str(count) for count in counts)
            + " |"
        )
        table = pl.read_parquet(declaration.catalogue / "products.parquet").sort("product_id")
        for row in table.iter_rows(named=True):
            products.append(f"| `{declared.provider_id}` | `{row['product_id']}` | `{row['unit']}` |")
    parts.extend(
        (
            "\n### Packaged product vocabulary\n",
            "Product identifiers and output units come from products.parquet. "
            "A provider listing a product does not imply that every station offers it. "
            "Use `find` and inspect availability for the selected series.\n",
            "| Provider | Product | Canonical unit |\n| --- | --- | --- |",
            *products,
        )
    )
    return "\n".join(parts).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated reference differs")
    args = parser.parse_args()
    destination = Path(__file__).resolve().parents[1] / "docs" / "reference.md"
    text = render_reference()
    if args.check:
        if not destination.exists() or destination.read_text(encoding="utf-8") != text:
            raise SystemExit("Reference drift: run uv run python scripts/generate_reference.py")
        print("Reference is current.")
    else:
        destination.write_text(text, encoding="utf-8")
        print(f"Wrote {destination}")


if __name__ == "__main__":
    main()
